name: 'Test Report'
on:
  workflow_run:
    workflows: ['Build and test']                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results            # artifact name
        name: JEST Tests                  # Name of the check run which will be created
        path: 'jest*.xml'                     # Path to test results (inside artifact .zip)
        reporter: jest-junit              # Format of test results
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results            # artifact name
        name: E2E Tests                  # Name of the check run which will be created
        path: 'codecept*.xml'                     # Path to test results (inside artifact .zip)
        reporter: jest-junit              # Format of test results